### ISSUE TITLE
Give user an idea of how much he can afford to send

### ISSUE THREAD

**Issue by abrkn** [krakenfx/swoop#3]

**Comment by ricburton** [comment]
Totally agree here. When I tried to fully empty the account the error I received was:

Deposit failed: Insufficient funds for gas \* price + value

This was a little confusing to start with, and then I realised that I had try and send less ether, but I wasn’t sure how much.

**Comment by stp-ip** [comment]
Had the same issue. Decided to collect the dust with https://www.myetherwallet.com/#send-transaction as I was not able to clean it out via the kraken tooling.

**Comment by abrkn** [comment]
See #9
