### ISSUE TITLE
Would be nice to be able to swoop complete wallet without me making calculations

### ISSUE THREAD

**Issue by gosuto-inzasheru** [krakenfx/swoop#6]
Left some dust behind now not sure how to clean my wallet...

**Comment by stp-ip** [comment]
I used https://www.myetherwallet.com/#send-transaction to sweep it clean.

**Comment by gosuto-inzasheru** [comment]
Nice one thanks!!

**Comment by martinkrung** [comment]
Same here. Not able empty wallet completly. How to calculate it?
"Deposit failed: Insufficient funds for gas \* price + value" What does this mean?

**Comment by abrkn** [comment]
See #9
