### ISSUE TITLE
"Deposit failed: Invalid JSON RPC response:"

### ISSUE THREAD

**Issue by FabianGerlinghaus** [krakenfx/swoop#8]
Trying to import my ether pre-sale wallet on https://www.kraken.com/ether/.
I left 3% for as fuel for the transfer. Not sure where the problem is.

**Comment by sycamorethetree** [comment]
Did anyone get back to you on this fabian?

**Comment by trapp** [comment]
Thanks for reporting.

This issue should be solved now. Please comment if it persists for you.

**Comment by pbosak** [comment]
Thank you, Timon!

2016-02-23 11:32 GMT+01:00 Timon Rapp <notifications@github.com>:

**Comment by t4t5** [comment]
This issue seems to have come back.

**Comment by ricburton** [comment]
I am seeing this error too.

**Comment by BTCLearner** [comment]
I too am seeing this error. Extremely useful tool, much appreciated if someone could take a look!

**Comment by 36zimmer** [comment]
same here
